services:
    php:
        container_name: alothaim-task
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - alothaim-task-network
        depends_on:
            mysql:
                condition: service_healthy
        restart: unless-stopped

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
            - "403:403"
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - alothaim-task-network

    mysql:
        image: mysql:8.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        networks:
            - alothaim-task-network
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$DB_USERNAME -p$DB_PASSWORD --silent"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    mysql-data:
        driver: local

networks:
    alothaim-task-network:
        driver: bridge
